CREATE TABLE "countries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_code" varchar(10) UNIQUE NOT NULL,
  "country_name" varchar(100) NOT NULL,
  "admin_level_1_label" varchar(50) NOT NULL,
  "admin_level_2_label" varchar(50) NOT NULL,
  "phone_code" varchar(10) NOT NULL,
  "currency_code" varchar(10) NOT NULL,
  "timezone" varchar(50) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "admin_level_1" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "code" varchar(20),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "admin_level_2" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_level_1_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "brands" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "department_id" integer NOT NULL,
  "niche_id" integer NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "niches" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "order_sources" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "shipping_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "expense_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "is_system_reserved" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "department_id" integer NOT NULL,
  "brand_id" integer NOT NULL,
  "type" varchar(50) NOT NULL,
  "category" varchar(100),
  "sku" varchar(100) UNIQUE,
  "price" decimal(12,2) NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'Active',
  "description" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "product_variants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "colour" varchar(100) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "inventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_id" integer,
  "waybill_stock" integer NOT NULL DEFAULT 0,
  "reserved" integer NOT NULL DEFAULT 0,
  "decremented" integer NOT NULL DEFAULT 0,
  "available" integer NOT NULL,
  "batch" varchar(100),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_bump_inventory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_id" integer,
  "waybill_stock" integer NOT NULL DEFAULT 0,
  "reserved" integer NOT NULL DEFAULT 0,
  "decremented" integer NOT NULL DEFAULT 0,
  "available" integer NOT NULL,
  "batch" varchar(100),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "can_edit_orders" boolean DEFAULT false,
  "can_delete_orders" boolean DEFAULT false,
  "can_view_finance" boolean DEFAULT false,
  "can_view_payroll" boolean DEFAULT false,
  "can_export_csv" boolean DEFAULT false,
  "can_manage_users" boolean DEFAULT false,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" integer NOT NULL,
  "username" varchar(100) UNIQUE NOT NULL,
  "display_name" varchar(100) NOT NULL,
  "full_name" varchar(200) NOT NULL,
  "email" varchar(200) UNIQUE NOT NULL,
  "phone" varchar(20),
  "password_hash" varchar(255) NOT NULL,
  "is_active" boolean DEFAULT true,
  "two_fa_enabled" boolean DEFAULT false,
  "two_fa_secret" varchar(255),
  "trusted_device_expires_at" timestamp,
  "last_login_at" timestamp,
  "last_logout_at" timestamp,
  "csr_level" integer DEFAULT 1,
  "is_on_break" boolean DEFAULT false,
  "created_by" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "department_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "employee_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "date_of_birth" date,
  "date_of_employment" date,
  "contact_address" text,
  "gender" varchar(20),
  "marital_status" varchar(50),
  "nationality" varchar(100),
  "state_of_origin" varchar(100),
  "lga_of_origin" varchar(100),
  "languages_spoken" varchar(200),
  "nin" varchar(255),
  "drivers_license" varchar(100),
  "tax_id" varchar(100),
  "next_of_kin_name" varchar(200),
  "next_of_kin_relationship" varchar(100),
  "next_of_kin_phone" varchar(20),
  "next_of_kin_address" text,
  "emergency_contact_name" varchar(200),
  "emergency_contact_relationship" varchar(100),
  "emergency_contact_phone_1" varchar(20),
  "emergency_contact_phone_2" varchar(20),
  "emergency_contact_address" text,
  "medical_conditions" text,
  "main_bank_name" varchar(100),
  "main_account_number" varchar(255),
  "main_account_type" varchar(50),
  "alternate_bank_name" varchar(100),
  "alternate_account_number" varchar(255),
  "alternate_account_type" varchar(50),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "session_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "logged_in_at" timestamp NOT NULL,
  "logged_out_at" timestamp,
  "session_duration_minutes" integer,
  "last_active_at" timestamp,
  "ip_address" varchar(50),
  "device_info" text
);

CREATE TABLE "customers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone_number" varchar(20) UNIQUE NOT NULL,
  "other_phone" varchar(20),
  "full_name" varchar(200),
  "email" varchar(200),
  "sex" varchar(20),
  "first_order_date" timestamp,
  "last_order_date" timestamp,
  "total_orders" integer DEFAULT 0,
  "total_purchases" integer DEFAULT 0,
  "lifetime_value" decimal(14,2) DEFAULT 0,
  "customer_tag" varchar(50) DEFAULT 'new',
  "is_banned" boolean DEFAULT false,
  "ban_reason" text,
  "banned_at" timestamp,
  "banned_by" integer,
  "csr_notes" text,
  "wati_opted_out" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "agents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "contact_name" varchar(200),
  "phone" varchar(20),
  "email" varchar(200),
  "address" text,
  "city" varchar(100),
  "admin_level_1_id" integer,
  "admin_level_2_id" integer,
  "bank_name" varchar(100),
  "account_number" varchar(50),
  "account_name" varchar(200),
  "status" varchar(50) DEFAULT 'Active',
  "ratings" decimal(3,1),
  "restrictions" text,
  "source" varchar(200),
  "whatsapp_group_name" varchar(200),
  "whatsapp_group_link" varchar(255),
  "comments" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "agent_zone_assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "admin_level_1_id" integer NOT NULL,
  "admin_level_2_id" integer,
  "primary_agent_id" integer NOT NULL,
  "overflow_agent_id" integer,
  "dispatch_rule" varchar(50) NOT NULL DEFAULT 'direct_assign',
  "zone_belt" varchar(100),
  "notes" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar(100) UNIQUE NOT NULL,
  "row_number" integer,
  "ordered_at" timestamp NOT NULL,
  "order_time" varchar(20),
  "scheduled_date" date,
  "date_paid" date,
  "first_contact_at" timestamp,
  "source_id" integer,
  "assigned_csr_id" integer NOT NULL,
  "department_id" integer NOT NULL,
  "brand_id" integer,
  "country_id" integer NOT NULL DEFAULT 1,
  "customer_id" integer,
  "customer_name" varchar(200) NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "other_phone" varchar(20),
  "email" varchar(200),
  "sex" varchar(20),
  "is_return_customer" boolean DEFAULT false,
  "admin_level_1_id" integer,
  "admin_level_2_id" integer,
  "city" varchar(200),
  "full_address" text,
  "status" varchar(100) NOT NULL DEFAULT 'Interested',
  "comments" text,
  "failure_reason_id" integer,
  "product_id" integer NOT NULL,
  "product_variant_id" integer,
  "quantity" integer NOT NULL DEFAULT 1,
  "price" decimal(12,2) NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "has_order_bump" boolean DEFAULT false,
  "order_bump_product_id" integer,
  "order_bump_variant_id" integer,
  "order_bump_quantity" integer DEFAULT 0,
  "order_bump_price" decimal(12,2) DEFAULT 0,
  "order_bump_type" varchar(100),
  "agent_id" integer,
  "logistics_fee" decimal(12,2),
  "shipping_type_id" integer,
  "niche_id" integer,
  "wati_sequence_triggered" boolean DEFAULT false,
  "wati_suppressed" boolean DEFAULT false,
  "api_batch_id" varchar(100),
  "late_cash_paid" boolean DEFAULT false,
  "is_test" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_id_counter" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prefix" varchar(20) NOT NULL DEFAULT 'CJAM',
  "last_number" integer NOT NULL DEFAULT 999,
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_status_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "previous_status" varchar(100),
  "new_status" varchar(100) NOT NULL,
  "changed_by" integer NOT NULL,
  "changed_at" timestamp DEFAULT (now()),
  "notes" text
);

CREATE TABLE "audit_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "action" varchar(100) NOT NULL,
  "table_name" varchar(100),
  "record_id" integer,
  "old_value" text,
  "new_value" text,
  "ip_address" varchar(50),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "agent_remittance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_id" integer NOT NULL,
  "admin_level_1_id" integer,
  "amount_remitted" decimal(14,2) NOT NULL,
  "logistics_fee_paid" decimal(14,2) DEFAULT 0,
  "final_amount_remitted" decimal(14,2) NOT NULL,
  "remittance_date" date NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "status" varchar(50) NOT NULL DEFAULT 'Pending_Bank_Verification',
  "logged_by" integer NOT NULL,
  "verified_by" integer,
  "verified_at" timestamp,
  "bank_reference" varchar(200),
  "actual_amount_received" decimal(14,2),
  "variance_amount" decimal(14,2),
  "variance_reason_id" integer,
  "dispute_notes" text,
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "expenses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "expense_category_id" integer NOT NULL,
  "description" text,
  "amount" decimal(14,2) NOT NULL,
  "expense_date" date NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "month" varchar(20),
  "year" integer,
  "product_id" integer,
  "agent_id" integer,
  "admin_level_1_id" integer,
  "batch" varchar(100),
  "comments" text,
  "receipt_url" varchar(500),
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "procurement_expenses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" text NOT NULL,
  "vendor_id" integer,
  "product_id" integer,
  "batch" varchar(100),
  "unit_quantity" integer NOT NULL,
  "unit_price_usd" decimal(10,4) NOT NULL,
  "shipping_usd" decimal(10,2) DEFAULT 0,
  "processing_fee_usd" decimal(10,2) DEFAULT 0,
  "alibaba_cut" decimal(10,4) DEFAULT 0,
  "total_usd" decimal(10,2) NOT NULL,
  "exchange_rate" decimal(10,2) NOT NULL,
  "total_ngn" decimal(14,2) NOT NULL,
  "procurement_date" date NOT NULL,
  "month" varchar(20),
  "year" integer,
  "niche_id" integer,
  "comments" text,
  "receipt_url" varchar(500),
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "ad_expenses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "brand_id" integer,
  "campaign_name" varchar(200),
  "time_period" varchar(100),
  "amount" decimal(14,2) NOT NULL,
  "platform" varchar(50),
  "payment_method" varchar(100),
  "expense_date" date NOT NULL,
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "receipt_url" varchar(500),
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "investment_inflow" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal(14,2) NOT NULL,
  "inflow_date" date NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "loans" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" decimal(14,2) NOT NULL,
  "loan_date" date NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "lender" varchar(200),
  "repayment_status" varchar(50) DEFAULT 'Outstanding',
  "amount_repaid" decimal(14,2) DEFAULT 0,
  "due_date" date,
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "payroll" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "amount" decimal(14,2) NOT NULL,
  "commission_amount" decimal(12,2) DEFAULT 0,
  "total_compensation" decimal(12,2),
  "payment_date" date,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "month" varchar(20),
  "year" integer,
  "payment_method" varchar(100),
  "bank_name" varchar(100),
  "account_number" varchar(50),
  "bank_reference" varchar(200),
  "status" varchar(50) DEFAULT 'Pending_Director_Approval',
  "director_approved_by" integer,
  "director_approved_at" timestamp,
  "comments" text,
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "taxes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tax_type" varchar(100) NOT NULL,
  "amount" decimal(14,2) NOT NULL,
  "tax_date" date NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "receipt_url" varchar(500),
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "goods_movement" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_id" integer,
  "quantity" integer NOT NULL,
  "movement_type" varchar(50) NOT NULL,
  "from_agent_id" integer,
  "to_agent_id" integer,
  "admin_level_1_id" integer,
  "shipping_type_id" integer,
  "movement_date" date NOT NULL,
  "batch" varchar(100),
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "complaints" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "customer_id" integer NOT NULL,
  "assigned_csr_id" integer,
  "complaint_type" varchar(100),
  "description" text NOT NULL,
  "resolution" text,
  "refund_amount" decimal(12,2) DEFAULT 0,
  "date_of_complaint" date,
  "replaced_or_refunded" boolean DEFAULT false,
  "cost_of_return" decimal(12,2) DEFAULT 0,
  "total_cost" decimal(12,2),
  "date_of_return" date,
  "status" varchar(50) DEFAULT 'Open',
  "logged_at" timestamp DEFAULT (now()),
  "resolved_at" timestamp,
  "resolved_by" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "trashed_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_id" integer,
  "quantity" integer NOT NULL,
  "agent_id" integer NOT NULL,
  "admin_level_1_id" integer,
  "status" varchar(50) NOT NULL DEFAULT 'Trashed',
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "logged_by" integer NOT NULL,
  "logged_at" date NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "notification_type" varchar(100) NOT NULL,
  "channel" varchar(50) NOT NULL,
  "recipient_type" varchar(50) NOT NULL,
  "recipient_user_id" integer,
  "recipient_agent_id" integer,
  "subject" varchar(200),
  "message" text,
  "status" varchar(50) DEFAULT 'Sent',
  "sent_at" timestamp DEFAULT (now()),
  "error_message" text
);

CREATE TABLE "waybill_expenses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "waybill_type" varchar(50) NOT NULL,
  "product_id" integer,
  "variant_id" integer,
  "quantity" integer,
  "batch" varchar(100),
  "colour" varchar(100),
  "waybill_status" varchar(50),
  "product_type" varchar(20),
  "from_admin_level_1_id" integer,
  "to_admin_level_1_id" integer,
  "agent_id" integer,
  "amount" decimal(14,2) NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "courier" varchar(100),
  "waybill_date" date NOT NULL,
  "payment_method" varchar(100),
  "month" varchar(20),
  "year" integer,
  "comments" text,
  "receipt_url" varchar(500),
  "logged_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "action_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "description" text,
  "assigned_to" integer,
  "assigned_by" integer,
  "status" varchar(50) DEFAULT 'Open',
  "priority" varchar(50) DEFAULT 'Medium',
  "due_date" date,
  "closed_at" timestamp,
  "closed_by" integer,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "csr_levels" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level_number" integer NOT NULL,
  "level_name" varchar(50) NOT NULL,
  "base_salary" decimal(12,2) NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "commission_tiers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department_id" integer NOT NULL,
  "payment_rate_min" decimal(5,2) NOT NULL,
  "payment_rate_max" decimal(5,2),
  "commission_per_unit" decimal(10,2) NOT NULL,
  "is_active" boolean DEFAULT true,
  "notes" text
);

CREATE TABLE "csr_promotion_thresholds" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department_id" integer NOT NULL,
  "from_level" integer NOT NULL,
  "to_level" integer NOT NULL,
  "direction" varchar(10) NOT NULL,
  "payment_rate_threshold" decimal(5,2) NOT NULL,
  "consecutive_months_required" integer NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "csr_level_history" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "previous_level" integer,
  "new_level" integer NOT NULL,
  "changed_at" timestamp DEFAULT (now()),
  "changed_by" integer,
  "reason" text
);

CREATE TABLE "csr_performance_monthly" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "department_id" integer NOT NULL,
  "month" varchar(20) NOT NULL,
  "year" integer NOT NULL,
  "total_orders" integer DEFAULT 0,
  "total_units_ordered" integer DEFAULT 0,
  "total_units_paid" integer DEFAULT 0,
  "payment_rate" decimal(5,2) DEFAULT 0,
  "commission_tier_id" integer,
  "commission_per_unit" decimal(10,2) DEFAULT 0,
  "total_commission" decimal(12,2) DEFAULT 0,
  "base_salary" decimal(12,2) DEFAULT 0,
  "total_compensation" decimal(12,2) DEFAULT 0,
  "csr_level_at_time" integer,
  "is_finalised" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "weekly_bonus_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "week_start_date" date NOT NULL,
  "week_end_date" date NOT NULL,
  "payment_rate_achieved" decimal(5,2) NOT NULL,
  "bonus_amount" decimal(10,2) NOT NULL DEFAULT 10000,
  "qualified" boolean NOT NULL,
  "announced_at" timestamp,
  "paid_at" timestamp,
  "paid_by" integer,
  "notes" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "failure_reason_codes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "description" varchar(200) NOT NULL,
  "applies_to_status" varchar(100),
  "is_active" boolean DEFAULT true
);

CREATE TABLE "pabbly_reconciliation_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reconciliation_date" date NOT NULL,
  "crm_order_count" integer NOT NULL,
  "pabbly_order_count" integer NOT NULL,
  "discrepancy" integer NOT NULL,
  "status" varchar(50) NOT NULL,
  "alert_sent" boolean DEFAULT false,
  "reviewed_by" integer,
  "reviewed_at" timestamp,
  "notes" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "backup_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "backup_type" varchar(50) NOT NULL,
  "file_name" varchar(200),
  "file_size_mb" decimal(8,2),
  "status" varchar(50) NOT NULL,
  "started_at" timestamp NOT NULL,
  "completed_at" timestamp,
  "error_message" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "wati_export_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "export_type" varchar(50) NOT NULL,
  "export_date" date NOT NULL,
  "records_exported" integer NOT NULL,
  "status" varchar(50) NOT NULL,
  "error_message" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "stock_adjustments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer NOT NULL,
  "variant_id" integer,
  "quantity_adjusted" integer NOT NULL,
  "adjustment_type" varchar(100) NOT NULL,
  "comments" text NOT NULL,
  "logged_by" integer NOT NULL,
  "approved_by" integer,
  "approved_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "agent_ledger" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_id" integer NOT NULL,
  "transaction_type" varchar(100) NOT NULL,
  "reference_id" integer,
  "reference_table" varchar(100),
  "debit_amount" decimal(14,2) DEFAULT 0,
  "credit_amount" decimal(14,2) DEFAULT 0,
  "running_balance" decimal(14,2) NOT NULL,
  "currency_code" varchar(10) DEFAULT 'NGN',
  "notes" text,
  "logged_by" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "department_targets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "department_id" integer NOT NULL,
  "base_conversion_rate" decimal(5,2) NOT NULL,
  "target_conversion_rate" decimal(5,2) NOT NULL,
  "planned_sales_rate" decimal(5,2) NOT NULL DEFAULT 70,
  "effective_from" date NOT NULL,
  "set_by" integer NOT NULL,
  "notes" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "vendors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "vendor_type" varchar(100),
  "phone_1" varchar(20),
  "phone_2" varchar(20),
  "address" text,
  "city" varchar(100),
  "admin_level_1_id" integer,
  "admin_level_2_id" integer,
  "country_id" integer,
  "comments" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "lesson_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "lessons_learned" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(300) NOT NULL,
  "content" text NOT NULL,
  "category_id" integer NOT NULL,
  "submitted_by" integer NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'Pending',
  "rejection_reason" text,
  "reviewed_by" integer,
  "reviewed_at" timestamp,
  "published_at" timestamp,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "escalation_reason_codes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(100) UNIQUE NOT NULL,
  "description" varchar(200) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_by" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "order_escalations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "reason_code_id" integer NOT NULL,
  "raised_by" integer NOT NULL,
  "raised_at" timestamp DEFAULT (now()),
  "csr_notes" text NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'Open',
  "resolved_by" integer,
  "resolved_at" timestamp,
  "resolution_action" varchar(100),
  "resolution_notes" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "remittance_variance_reason_codes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(100) UNIQUE NOT NULL,
  "description" varchar(200) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "auditor_check_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(100) UNIQUE NOT NULL,
  "description" varchar(200) NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "auditor_spot_checks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "auditor_id" integer NOT NULL,
  "check_date" date NOT NULL DEFAULT (CURRENT_DATE),
  "check_category_id" integer NOT NULL,
  "result" varchar(50) NOT NULL,
  "auditor_notes" text,
  "escalated_to_director" boolean DEFAULT false,
  "director_reviewed_at" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "weekly_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "report_type" varchar(50) NOT NULL,
  "department_id" integer,
  "csr_id" integer,
  "week_start_date" date NOT NULL,
  "week_end_date" date NOT NULL,
  "providus_inflow" decimal(14,2),
  "providus_outflow" decimal(14,2),
  "providus_comments" text,
  "moniepoint_inflow" decimal(14,2),
  "moniepoint_outflow" decimal(14,2),
  "moniepoint_comments" text,
  "accountant_notes" text,
  "cash_flow_logged" boolean DEFAULT false,
  "ops_aob" text,
  "csr_aob" text,
  "generated_by" integer NOT NULL,
  "pdf_url" varchar(500),
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "countries"."country_code" IS 'ISO code e.g. NG, GH, KE';

COMMENT ON COLUMN "countries"."admin_level_1_label" IS 'State for Nigeria, Region for Ghana';

COMMENT ON COLUMN "countries"."admin_level_2_label" IS 'LGA for Nigeria, District for Ghana';

COMMENT ON COLUMN "countries"."phone_code" IS '+234 for Nigeria, +233 for Ghana';

COMMENT ON COLUMN "countries"."currency_code" IS 'NGN, GHS, KES etc';

COMMENT ON COLUMN "countries"."timezone" IS 'Africa/Lagos, Africa/Accra etc';

COMMENT ON COLUMN "admin_level_1"."code" IS 'e.g. LA for Lagos, AB for Abuja';

COMMENT ON COLUMN "expense_categories"."is_system_reserved" IS 'If true, only automated processes can write to this category. Not shown in manual expense dropdown.';

COMMENT ON COLUMN "products"."type" IS 'Main, Order Bump, Upsell';

COMMENT ON COLUMN "products"."status" IS 'Active, Inactive, Out of Stock';

COMMENT ON COLUMN "inventory"."waybill_stock" IS 'Total stock received from supplier';

COMMENT ON COLUMN "inventory"."reserved" IS 'Soft allocated — order status is Pending';

COMMENT ON COLUMN "inventory"."decremented" IS 'Permanently removed — order status is Cash Paid';

COMMENT ON COLUMN "inventory"."available" IS 'PostgreSQL GENERATED ALWAYS AS (waybill_stock - reserved - decremented) STORED — do not allow app to insert this value';

COMMENT ON COLUMN "inventory"."batch" IS 'Batch One, Batch Two etc';

COMMENT ON COLUMN "order_bump_inventory"."available" IS 'PostgreSQL GENERATED ALWAYS AS (waybill_stock - reserved - decremented) STORED — do not allow app to insert this value';

COMMENT ON COLUMN "users"."username" IS 'Auto-generated: firstname.lastinitial e.g. ohambele.f';

COMMENT ON COLUMN "users"."display_name" IS 'Short name shown in dropdowns e.g. Ohambele';

COMMENT ON COLUMN "users"."full_name" IS 'Legal name e.g. Ohambele Faith Chinonye';

COMMENT ON COLUMN "users"."email" IS 'Company email e.g. ohambele.chinonye@jamisan.com';

COMMENT ON COLUMN "users"."is_active" IS 'Director can disable instantly';

COMMENT ON COLUMN "users"."trusted_device_expires_at" IS '30-day trusted device period for 2FA roles';

COMMENT ON COLUMN "users"."csr_level" IS 'Current CSR level 1-5. Only relevant for CSR role.';

COMMENT ON COLUMN "users"."is_on_break" IS 'CSR-only. Clicking On Break toggle sets this to true instantly. Overrides last_active_at timer and sets status to Away (Yellow) immediately. Cleared on next CRM action.';

COMMENT ON COLUMN "users"."created_by" IS 'user_id of Director or HR Manager who created this account';

COMMENT ON COLUMN "employee_profiles"."nin" IS 'ENCRYPTED AT REST — use pgcrypto or app-level encryption before storing';

COMMENT ON COLUMN "employee_profiles"."medical_conditions" IS 'ENCRYPTED AT REST — sensitive health information';

COMMENT ON COLUMN "employee_profiles"."main_account_number" IS 'ENCRYPTED AT REST — financial PII';

COMMENT ON COLUMN "employee_profiles"."main_account_type" IS 'Savings or Current';

COMMENT ON COLUMN "employee_profiles"."alternate_account_number" IS 'ENCRYPTED AT REST — financial PII';

COMMENT ON COLUMN "session_log"."session_duration_minutes" IS 'Calculated on logout';

COMMENT ON COLUMN "session_log"."last_active_at" IS 'Updated on every API request from the user. Delta between this and now() determines Green/Yellow/Red status on Ops Manager Live Floor.';

COMMENT ON COLUMN "customers"."phone_number" IS 'Primary identifier. Format: +234XXXXXXXXXX';

COMMENT ON COLUMN "customers"."sex" IS 'Male, Female, Undefined';

COMMENT ON COLUMN "customers"."total_orders" IS 'All orders ever placed';

COMMENT ON COLUMN "customers"."total_purchases" IS 'Cash Paid orders only';

COMMENT ON COLUMN "customers"."lifetime_value" IS 'Total amount paid across all orders';

COMMENT ON COLUMN "customers"."customer_tag" IS 'new, ordered_not_bought, bought';

COMMENT ON COLUMN "customers"."banned_by" IS 'user_id of Director or CSR who set the ban';

COMMENT ON COLUMN "customers"."csr_notes" IS 'Freeform notes at customer level — separate from order comments';

COMMENT ON COLUMN "customers"."wati_opted_out" IS 'Reset to false on new order';

COMMENT ON COLUMN "agents"."name" IS 'Company name e.g. Parcel Exchange, RGMARTZ';

COMMENT ON COLUMN "agents"."contact_name" IS 'Individual contact at the agent company';

COMMENT ON COLUMN "agents"."admin_level_1_id" IS 'Primary state of operation';

COMMENT ON COLUMN "agents"."admin_level_2_id" IS 'Agent warehouse LGA';

COMMENT ON COLUMN "agents"."status" IS 'Active, Inactive';

COMMENT ON COLUMN "agents"."ratings" IS 'Performance score out of 5';

COMMENT ON COLUMN "agents"."restrictions" IS 'Any delivery restrictions for this agent';

COMMENT ON COLUMN "agents"."source" IS 'How agent was recruited';

COMMENT ON COLUMN "agents"."whatsapp_group_name" IS 'Name of the WhatsApp group for this agent e.g. Shanoma Logistics Jamisan';

COMMENT ON COLUMN "agents"."whatsapp_group_link" IS 'WhatsApp group invite link for CSR copy-paste routing';

COMMENT ON COLUMN "agent_zone_assignments"."admin_level_1_id" IS 'State';

COMMENT ON COLUMN "agent_zone_assignments"."admin_level_2_id" IS 'LGA — null means entire state';

COMMENT ON COLUMN "agent_zone_assignments"."overflow_agent_id" IS 'Activated when primary agent unavailable';

COMMENT ON COLUMN "agent_zone_assignments"."dispatch_rule" IS 'direct_assign, round_robin, overflow_only';

COMMENT ON COLUMN "agent_zone_assignments"."zone_belt" IS 'Western, Eastern, Northern, Metro etc';

COMMENT ON COLUMN "agent_zone_assignments"."notes" IS 'Routing rationale and special instructions';

COMMENT ON COLUMN "orders"."order_id" IS 'Auto-generated e.g. CJAM1000. C=CRM, JAM=Jamisan, number increments from 1000';

COMMENT ON COLUMN "orders"."row_number" IS 'Sequential display number — mirrors # column in Google Sheets';

COMMENT ON COLUMN "orders"."ordered_at" IS 'Date and time order was placed';

COMMENT ON COLUMN "orders"."order_time" IS 'Time string from Jamisan Form';

COMMENT ON COLUMN "orders"."scheduled_date" IS 'For customers who request a callback or later delivery';

COMMENT ON COLUMN "orders"."date_paid" IS 'Date customer payment was confirmed';

COMMENT ON COLUMN "orders"."first_contact_at" IS 'Auto-stamped when CSR first updates status from Interested';

COMMENT ON COLUMN "orders"."source_id" IS 'Jamisan Form, WhatsApp Form, Social Media';

COMMENT ON COLUMN "orders"."assigned_csr_id" IS 'Set by Pabbly on order creation';

COMMENT ON COLUMN "orders"."department_id" IS 'Inherited from product via brand';

COMMENT ON COLUMN "orders"."brand_id" IS 'Brand source of the order';

COMMENT ON COLUMN "orders"."country_id" IS 'Defaults to Nigeria';

COMMENT ON COLUMN "orders"."customer_id" IS 'Links to customers table via phone_number lookup';

COMMENT ON COLUMN "orders"."phone_number" IS 'Auto-formatted to +234XXXXXXXXXX';

COMMENT ON COLUMN "orders"."other_phone" IS 'Auto-formatted to +234XXXXXXXXXX';

COMMENT ON COLUMN "orders"."sex" IS 'Male, Female, Undefined — set by CSR';

COMMENT ON COLUMN "orders"."is_return_customer" IS 'Auto-set by CRM on order creation';

COMMENT ON COLUMN "orders"."admin_level_1_id" IS 'State — drives agent dropdown filter';

COMMENT ON COLUMN "orders"."admin_level_2_id" IS 'LGA — cascades from state selection';

COMMENT ON COLUMN "orders"."status" IS 'One of 32 statuses. See spec Day 1 Section 4.';

COMMENT ON COLUMN "orders"."comments" IS 'CSR adds context when updating status';

COMMENT ON COLUMN "orders"."failure_reason_id" IS 'Mandatory for Failed, Cancelled, Returned orders — cannot be blank';

COMMENT ON COLUMN "orders"."product_variant_id" IS 'Colour selected';

COMMENT ON COLUMN "orders"."price" IS 'Editable if customer haggles — reason logged in comments';

COMMENT ON COLUMN "orders"."order_bump_product_id" IS 'Order Bump product if applicable';

COMMENT ON COLUMN "orders"."order_bump_variant_id" IS 'Order Bump colour';

COMMENT ON COLUMN "orders"."order_bump_price" IS 'Editable price for order bump — may differ from product default price. Required for P&L and Copy Order clipboard.';

COMMENT ON COLUMN "orders"."order_bump_type" IS 'Physical or Digital — determines stock deduction logic';

COMMENT ON COLUMN "orders"."agent_id" IS 'Assigned by CSR from state-filtered dropdown';

COMMENT ON COLUMN "orders"."logistics_fee" IS 'Delivery fee — logged by CSR after agent confirms';

COMMENT ON COLUMN "orders"."niche_id" IS 'Inherited from brand — for reporting';

COMMENT ON COLUMN "orders"."wati_sequence_triggered" IS 'True when order exported to Cash Paid sheet';

COMMENT ON COLUMN "orders"."wati_suppressed" IS 'Set true when complaint or refund logged against this order';

COMMENT ON COLUMN "orders"."api_batch_id" IS 'Pabbly webhook batch ID — traces Round-Robin assignment back to exact webhook payload for debugging. Shown in right panel Part B of slide-out panel.';

COMMENT ON COLUMN "orders"."late_cash_paid" IS 'Set true when order transitions Abandoned → Cash Paid. Signals CSR neglect or agent delivering outside 72hr SLA. Visible in Auditor Rapid Fail queue and Director dashboard.';

COMMENT ON COLUMN "orders"."is_test" IS 'Test orders filtered from all reports';

COMMENT ON COLUMN "order_id_counter"."prefix" IS 'C=CRM, JAM=Jamisan. Never changes.';

COMMENT ON COLUMN "order_id_counter"."last_number" IS 'Seed value — sequence starts at 1000. Use PostgreSQL SEQUENCE not this field directly.';

COMMENT ON COLUMN "order_status_history"."changed_by" IS 'user_id of CSR or system';

COMMENT ON COLUMN "order_status_history"."notes" IS 'Optional context for the status change';

COMMENT ON COLUMN "audit_log"."action" IS 'e.g. edit_order, delete_order, login, export_csv';

COMMENT ON COLUMN "audit_log"."table_name" IS 'Which table was affected';

COMMENT ON COLUMN "audit_log"."record_id" IS 'Which record was affected';

COMMENT ON COLUMN "audit_log"."old_value" IS 'JSON snapshot of record before change';

COMMENT ON COLUMN "audit_log"."new_value" IS 'JSON snapshot of record after change';

COMMENT ON COLUMN "agent_remittance"."admin_level_1_id" IS 'State the remittance covers';

COMMENT ON COLUMN "agent_remittance"."amount_remitted" IS 'Raw cash received from agent';

COMMENT ON COLUMN "agent_remittance"."logistics_fee_paid" IS 'Logistics fee deducted from remittance';

COMMENT ON COLUMN "agent_remittance"."final_amount_remitted" IS 'amount_remitted - logistics_fee_paid';

COMMENT ON COLUMN "agent_remittance"."currency_code" IS 'NGN for Nigeria, GHS for Ghana etc';

COMMENT ON COLUMN "agent_remittance"."status" IS 'Pending_Bank_Verification, Verified_Cleared, Disputed';

COMMENT ON COLUMN "agent_remittance"."logged_by" IS 'Ops Manager user_id who logged the remittance';

COMMENT ON COLUMN "agent_remittance"."verified_by" IS 'Accountant user_id who verified against bank statement';

COMMENT ON COLUMN "agent_remittance"."verified_at" IS 'When Accountant clicked Verified and Cleared';

COMMENT ON COLUMN "agent_remittance"."bank_reference" IS 'Bank transfer reference number — added by Accountant on verification';

COMMENT ON COLUMN "agent_remittance"."actual_amount_received" IS 'Actual amount seen in bank statement — may differ from amount_remitted';

COMMENT ON COLUMN "agent_remittance"."variance_amount" IS 'actual_amount_received - final_amount_remitted. Negative = shortage, positive = overpayment';

COMMENT ON COLUMN "agent_remittance"."variance_reason_id" IS 'Reason for variance — from remittance_variance_reason_codes table';

COMMENT ON COLUMN "agent_remittance"."dispute_notes" IS 'Populated when Accountant flags a discrepancy';

COMMENT ON COLUMN "expenses"."product_id" IS 'If expense is tied to a specific product';

COMMENT ON COLUMN "expenses"."agent_id" IS 'If expense is tied to a specific agent';

COMMENT ON COLUMN "expenses"."admin_level_1_id" IS 'If expense is tied to a specific state';

COMMENT ON COLUMN "expenses"."batch" IS 'If expense is tied to a procurement batch';

COMMENT ON COLUMN "expenses"."receipt_url" IS 'Google Drive shareable link to receipt — Accountant uploads to Drive, pastes link here';

COMMENT ON COLUMN "procurement_expenses"."vendor_id" IS 'Links to vendors table — Vendor dropdown in Accountant procurement form. Chain link icon opens vendor profile.';

COMMENT ON COLUMN "procurement_expenses"."unit_quantity" IS 'Number of units purchased';

COMMENT ON COLUMN "procurement_expenses"."unit_price_usd" IS 'Cost per unit in USD';

COMMENT ON COLUMN "procurement_expenses"."shipping_usd" IS 'Shipping cost in USD';

COMMENT ON COLUMN "procurement_expenses"."alibaba_cut" IS 'Alibaba commission percentage';

COMMENT ON COLUMN "procurement_expenses"."total_usd" IS 'Total cost in USD before conversion';

COMMENT ON COLUMN "procurement_expenses"."exchange_rate" IS 'USD to NGN rate at time of purchase';

COMMENT ON COLUMN "procurement_expenses"."total_ngn" IS 'total_usd * exchange_rate';

COMMENT ON COLUMN "procurement_expenses"."receipt_url" IS 'Google Drive shareable link to invoice or receipt';

COMMENT ON COLUMN "ad_expenses"."campaign_name" IS 'e.g. Stretchmarks Gel ABO, Speaker CBO';

COMMENT ON COLUMN "ad_expenses"."time_period" IS 'e.g. January, Q1 2025, Week 3';

COMMENT ON COLUMN "ad_expenses"."platform" IS 'Facebook, TikTok, Google etc';

COMMENT ON COLUMN "ad_expenses"."payment_method" IS 'Company Card, Bank Transfer, Petty Cash';

COMMENT ON COLUMN "ad_expenses"."receipt_url" IS 'Google Drive link to screenshot from Ads Manager';

COMMENT ON COLUMN "investment_inflow"."comments" IS 'e.g. Investment Inflow from Director';

COMMENT ON COLUMN "investment_inflow"."logged_by" IS 'Director user_id';

COMMENT ON COLUMN "loans"."repayment_status" IS 'Outstanding, Partially Paid, Fully Paid';

COMMENT ON COLUMN "payroll"."amount" IS 'Base salary';

COMMENT ON COLUMN "payroll"."commission_amount" IS 'Calculated from csr_performance_monthly';

COMMENT ON COLUMN "payroll"."total_compensation" IS 'amount + commission_amount';

COMMENT ON COLUMN "payroll"."bank_reference" IS 'Bank transfer reference number logged by Accountant after external payment';

COMMENT ON COLUMN "payroll"."status" IS 'Pending_Director_Approval, Approved, Paid, On_Hold';

COMMENT ON COLUMN "payroll"."director_approved_by" IS 'Director user_id who approved the payroll batch';

COMMENT ON COLUMN "payroll"."director_approved_at" IS 'When Director clicked Approve Batch';

COMMENT ON COLUMN "payroll"."logged_by" IS 'HR user_id who prepared the payroll';

COMMENT ON COLUMN "taxes"."tax_type" IS 'VAT, Corporate Tax, PAYE etc';

COMMENT ON COLUMN "taxes"."receipt_url" IS 'Google Drive link to tax payment receipt or assessment document';

COMMENT ON COLUMN "goods_movement"."movement_type" IS 'Sent, Returned, Waybill';

COMMENT ON COLUMN "goods_movement"."from_agent_id" IS 'Null means Jamisan warehouse is the source';

COMMENT ON COLUMN "goods_movement"."to_agent_id" IS 'Null means returning to Jamisan warehouse';

COMMENT ON COLUMN "goods_movement"."admin_level_1_id" IS 'State goods moved to or from';

COMMENT ON COLUMN "complaints"."assigned_csr_id" IS 'CSR who logged the complaint';

COMMENT ON COLUMN "complaints"."complaint_type" IS 'Wrong Product, Late Delivery, Damaged Item, Other';

COMMENT ON COLUMN "complaints"."resolution" IS 'How it was resolved';

COMMENT ON COLUMN "complaints"."refund_amount" IS 'Amount refunded if applicable';

COMMENT ON COLUMN "complaints"."total_cost" IS 'cost_of_return + refund_amount';

COMMENT ON COLUMN "complaints"."status" IS 'Open, Resolved, Escalated';

COMMENT ON COLUMN "complaints"."resolved_by" IS 'user_id of CSR or Director who resolved';

COMMENT ON COLUMN "trashed_items"."agent_id" IS 'Agent who returned the item';

COMMENT ON COLUMN "trashed_items"."admin_level_1_id" IS 'State the item was returned from';

COMMENT ON COLUMN "trashed_items"."status" IS 'Trashed, Redistributed';

COMMENT ON COLUMN "trashed_items"."logged_by" IS 'Warehouse Coordinator user_id';

COMMENT ON COLUMN "notifications"."notification_type" IS 'csr_alert, login_alert, agent_summary, daily_hygiene, abandoned_instant';

COMMENT ON COLUMN "notifications"."channel" IS 'email, whatsapp, internal';

COMMENT ON COLUMN "notifications"."recipient_type" IS 'user, agent';

COMMENT ON COLUMN "notifications"."recipient_user_id" IS 'If sent to a staff member';

COMMENT ON COLUMN "notifications"."recipient_agent_id" IS 'If sent to an agent';

COMMENT ON COLUMN "notifications"."status" IS 'Sent, Failed, Pending';

COMMENT ON COLUMN "notifications"."error_message" IS 'If status is Failed, reason stored here';

COMMENT ON COLUMN "waybill_expenses"."waybill_type" IS 'Sending, Receiving';

COMMENT ON COLUMN "waybill_expenses"."waybill_status" IS 'Warehouse, Signed Receipt, In Transit';

COMMENT ON COLUMN "waybill_expenses"."product_type" IS 'Main or Order Bump';

COMMENT ON COLUMN "waybill_expenses"."from_admin_level_1_id" IS 'State goods shipped from';

COMMENT ON COLUMN "waybill_expenses"."to_admin_level_1_id" IS 'State goods shipped to';

COMMENT ON COLUMN "waybill_expenses"."agent_id" IS 'Agent involved in the waybill';

COMMENT ON COLUMN "waybill_expenses"."amount" IS 'Cost of the waybill';

COMMENT ON COLUMN "waybill_expenses"."courier" IS 'Courier company used';

COMMENT ON COLUMN "waybill_expenses"."payment_method" IS 'Company paid, Agent to Pay and Deduct, Petty Cash';

COMMENT ON COLUMN "waybill_expenses"."receipt_url" IS 'Google Drive link to waybill receipt or transport invoice';

COMMENT ON COLUMN "action_items"."assigned_to" IS 'user_id of staff member responsible';

COMMENT ON COLUMN "action_items"."assigned_by" IS 'user_id of Director or Ops Manager who created it';

COMMENT ON COLUMN "action_items"."status" IS 'Open, In Progress, Closed';

COMMENT ON COLUMN "action_items"."priority" IS 'Low, Medium, High, Critical';

COMMENT ON COLUMN "csr_levels"."level_number" IS '1 through 5';

COMMENT ON COLUMN "csr_levels"."level_name" IS 'Level 1, Level 2 etc';

COMMENT ON COLUMN "csr_levels"."base_salary" IS 'L1=100k L2=150k L3=180k L4=220k L5=270k';

COMMENT ON COLUMN "commission_tiers"."payment_rate_min" IS 'Lower bound e.g. 40.00';

COMMENT ON COLUMN "commission_tiers"."payment_rate_max" IS 'Upper bound — null means no ceiling';

COMMENT ON COLUMN "commission_tiers"."commission_per_unit" IS 'Naira per paid unit';

COMMENT ON COLUMN "commission_tiers"."notes" IS 'e.g. Transition period for gadgets';

COMMENT ON COLUMN "csr_promotion_thresholds"."from_level" IS 'Current level';

COMMENT ON COLUMN "csr_promotion_thresholds"."to_level" IS 'Target level';

COMMENT ON COLUMN "csr_promotion_thresholds"."direction" IS 'promotion or demotion';

COMMENT ON COLUMN "csr_promotion_thresholds"."consecutive_months_required" IS '3 for promotion, 2 for demotion';

COMMENT ON COLUMN "csr_level_history"."changed_by" IS 'Director or Ops Manager user_id for manual changes. NULL for automated promotions triggered by csr_promotion_thresholds.';

COMMENT ON COLUMN "csr_level_history"."reason" IS 'Grace provision applied, sustained performance etc';

COMMENT ON COLUMN "csr_performance_monthly"."total_units_paid" IS 'Cash Paid orders only';

COMMENT ON COLUMN "csr_performance_monthly"."payment_rate" IS 'total_units_paid / total_units_ordered * 100';

COMMENT ON COLUMN "csr_performance_monthly"."commission_tier_id" IS 'Which tier applied this month';

COMMENT ON COLUMN "csr_performance_monthly"."total_compensation" IS 'base_salary + total_commission';

COMMENT ON COLUMN "csr_performance_monthly"."csr_level_at_time" IS 'Level CSR was at during this month';

COMMENT ON COLUMN "csr_performance_monthly"."is_finalised" IS 'Locked once payroll is processed';

COMMENT ON COLUMN "weekly_bonus_log"."qualified" IS 'False if nobody crossed 40% that week';

COMMENT ON COLUMN "weekly_bonus_log"."paid_by" IS 'Ops Manager user_id';

COMMENT ON COLUMN "failure_reason_codes"."description" IS 'e.g. Customer Refused, Wrong Address, Unreachable';

COMMENT ON COLUMN "failure_reason_codes"."applies_to_status" IS 'Failed, Cancelled, Returned etc';

COMMENT ON COLUMN "pabbly_reconciliation_log"."discrepancy" IS 'crm_order_count - pabbly_order_count';

COMMENT ON COLUMN "pabbly_reconciliation_log"."status" IS 'Matched, Discrepancy Found';

COMMENT ON COLUMN "pabbly_reconciliation_log"."reviewed_by" IS 'Ops Manager or Director who reviewed';

COMMENT ON COLUMN "backup_log"."backup_type" IS 'local, offsite';

COMMENT ON COLUMN "backup_log"."status" IS 'Success, Failed, In Progress';

COMMENT ON COLUMN "wati_export_log"."export_type" IS 'cash_paid_orders, complaints_refunds';

COMMENT ON COLUMN "wati_export_log"."status" IS 'Success, Failed';

COMMENT ON COLUMN "stock_adjustments"."quantity_adjusted" IS 'Positive = surplus found. Negative = shrinkage/loss.';

COMMENT ON COLUMN "stock_adjustments"."adjustment_type" IS 'Shrinkage/Missing, Damaged_In_Warehouse, Marketing_Sample, Found/Surplus, Initial_Count_Correction';

COMMENT ON COLUMN "stock_adjustments"."comments" IS 'Mandatory — must explain reason for adjustment';

COMMENT ON COLUMN "stock_adjustments"."logged_by" IS 'Warehouse Coordinator, Ops Manager, or Director';

COMMENT ON COLUMN "stock_adjustments"."approved_by" IS 'Director approval required if adjustment pushes available below zero';

COMMENT ON COLUMN "agent_ledger"."transaction_type" IS 'Order_Delivered, Logistics_Fee_Retained, Waybill_Paid_By_Agent, Return_Fee_Retained, Cash_Remitted, Manual_Adjustment';

COMMENT ON COLUMN "agent_ledger"."reference_id" IS 'order_id, waybill_id, or remittance_id — links to source record';

COMMENT ON COLUMN "agent_ledger"."reference_table" IS 'orders, waybill_expenses, or agent_remittance — identifies which table reference_id points to';

COMMENT ON COLUMN "agent_ledger"."debit_amount" IS 'Cash agent owes Jamisan';

COMMENT ON COLUMN "agent_ledger"."credit_amount" IS 'Cash Jamisan owes agent OR cash agent remitted';

COMMENT ON COLUMN "agent_ledger"."running_balance" IS 'Calculated by trigger: previous_balance + debit_amount - credit_amount';

COMMENT ON COLUMN "agent_ledger"."notes" IS 'Auto-populated from source record. Manual entries require explicit reason.';

COMMENT ON COLUMN "agent_ledger"."logged_by" IS 'System for auto-entries. Director user_id for manual adjustments.';

COMMENT ON COLUMN "department_targets"."department_id" IS 'NOT unique — multiple rows per department allowed for historical tracking. Query uses effective_from to get the active rate at any point in time.';

COMMENT ON COLUMN "department_targets"."base_conversion_rate" IS 'Minimum acceptable rate e.g. 35.00 for Gadgets';

COMMENT ON COLUMN "department_targets"."target_conversion_rate" IS 'Strong performer rate e.g. 40.00 for Gadgets';

COMMENT ON COLUMN "department_targets"."planned_sales_rate" IS 'Used for Planned Sales calc on CSR report. Was hardcoded 70% in Google Sheets.';

COMMENT ON COLUMN "department_targets"."effective_from" IS 'When this target set came into effect';

COMMENT ON COLUMN "department_targets"."set_by" IS 'Director who set the targets';

COMMENT ON COLUMN "department_targets"."notes" IS 'Reason for target change if applicable';

COMMENT ON COLUMN "vendors"."vendor_type" IS 'Shipping Agent, Warehouse Agent, Packaging Supplier, Print Supplier, Other';

COMMENT ON COLUMN "vendors"."admin_level_1_id" IS 'State/Region';

COMMENT ON COLUMN "vendors"."admin_level_2_id" IS 'LGA/District';

COMMENT ON COLUMN "vendors"."country_id" IS 'Defaults to Nigeria';

COMMENT ON COLUMN "vendors"."comments" IS 'Describe the service this vendor provides';

COMMENT ON COLUMN "lesson_categories"."name" IS 'Sales Script, Logistics Warning, CRM SOP, Fraud Prevention, Other';

COMMENT ON COLUMN "lesson_categories"."created_by" IS 'Director user_id';

COMMENT ON COLUMN "lessons_learned"."content" IS 'Rich text — sales scripts, SOPs, warnings, tactics';

COMMENT ON COLUMN "lessons_learned"."submitted_by" IS 'Any staff member — user_id';

COMMENT ON COLUMN "lessons_learned"."status" IS 'Pending, Published, Rejected';

COMMENT ON COLUMN "lessons_learned"."rejection_reason" IS 'Director must provide reason if rejecting';

COMMENT ON COLUMN "lessons_learned"."reviewed_by" IS 'Director user_id';

COMMENT ON COLUMN "escalation_reason_codes"."created_by" IS 'Director user_id — Directors manage these codes';

COMMENT ON COLUMN "order_escalations"."raised_by" IS 'user_id of staff member who raised the escalation — CSR for order flags, Auditor for Auditor_Flag reason code';

COMMENT ON COLUMN "order_escalations"."csr_notes" IS 'Mandatory explanation from CSR — cannot be blank';

COMMENT ON COLUMN "order_escalations"."status" IS 'Open, Approved, Rejected, Reassigned';

COMMENT ON COLUMN "order_escalations"."resolved_by" IS 'Ops Manager or Director user_id who resolved';

COMMENT ON COLUMN "order_escalations"."resolution_action" IS 'Unban_User, Approve_Zero_Fee, Reassign, Reject, Investigate';

COMMENT ON COLUMN "order_escalations"."resolution_notes" IS 'Ops Manager explanation of action taken';

COMMENT ON COLUMN "auditor_spot_checks"."result" IS 'Pass, Flagged';

COMMENT ON COLUMN "weekly_reports"."report_type" IS 'CSR_Personal, Ops_Full';

COMMENT ON COLUMN "weekly_reports"."department_id" IS 'Department this report covers';

COMMENT ON COLUMN "weekly_reports"."csr_id" IS 'For CSR_Personal reports — which CSR this belongs to';

COMMENT ON COLUMN "weekly_reports"."providus_inflow" IS 'Total cash received into Providus account for the week';

COMMENT ON COLUMN "weekly_reports"."providus_outflow" IS 'Total cash paid out of Providus account for the week';

COMMENT ON COLUMN "weekly_reports"."providus_comments" IS 'Accountant narrative on Providus activity e.g. major receipts or payments';

COMMENT ON COLUMN "weekly_reports"."moniepoint_inflow" IS 'Total cash received into Moniepoint account for the week';

COMMENT ON COLUMN "weekly_reports"."moniepoint_outflow" IS 'Total cash paid out of Moniepoint account for the week';

COMMENT ON COLUMN "weekly_reports"."moniepoint_comments" IS 'Accountant narrative on Moniepoint activity';

COMMENT ON COLUMN "weekly_reports"."accountant_notes" IS 'Section 9 closing notes — mandatory before Generate button activates';

COMMENT ON COLUMN "weekly_reports"."cash_flow_logged" IS 'Set true when Accountant saves Section 9 fields. Generate button blocked until true. Clears Pending Actions reminder.';

COMMENT ON COLUMN "weekly_reports"."ops_aob" IS 'Section 10 — Any Other Business entered by Ops Manager before PDF generation';

COMMENT ON COLUMN "weekly_reports"."csr_aob" IS 'Any Other Business entered by CSR for their Section 3 personal report';

COMMENT ON COLUMN "weekly_reports"."generated_by" IS 'user_id of whoever clicked Generate';

COMMENT ON COLUMN "weekly_reports"."pdf_url" IS 'Google Drive link to archived PDF — same pattern as expense receipts';

ALTER TABLE "admin_level_1" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "admin_level_2" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "brands" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "brands" ADD FOREIGN KEY ("niche_id") REFERENCES "niches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "inventory" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_bump_inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_bump_inventory" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_departments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_departments" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "employee_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "session_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customers" ADD FOREIGN KEY ("banned_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agents" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agents" ADD FOREIGN KEY ("admin_level_2_id") REFERENCES "admin_level_2" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_zone_assignments" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_zone_assignments" ADD FOREIGN KEY ("admin_level_2_id") REFERENCES "admin_level_2" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_zone_assignments" ADD FOREIGN KEY ("primary_agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_zone_assignments" ADD FOREIGN KEY ("overflow_agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("source_id") REFERENCES "order_sources" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("assigned_csr_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("admin_level_2_id") REFERENCES "admin_level_2" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("order_bump_product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("order_bump_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("shipping_type_id") REFERENCES "shipping_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("niche_id") REFERENCES "niches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("failure_reason_id") REFERENCES "failure_reason_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "audit_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_remittance" ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_remittance" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_remittance" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("expense_category_id") REFERENCES "expense_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "procurement_expenses" ADD FOREIGN KEY ("vendor_id") REFERENCES "vendors" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "procurement_expenses" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "procurement_expenses" ADD FOREIGN KEY ("niche_id") REFERENCES "niches" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "procurement_expenses" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ad_expenses" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ad_expenses" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ad_expenses" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "investment_inflow" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "loans" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payroll" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payroll" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payroll" ADD FOREIGN KEY ("director_approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "taxes" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("from_agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("to_agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("shipping_type_id") REFERENCES "shipping_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_movement" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "complaints" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "complaints" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "complaints" ADD FOREIGN KEY ("assigned_csr_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "complaints" ADD FOREIGN KEY ("resolved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trashed_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trashed_items" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trashed_items" ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trashed_items" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "trashed_items" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("recipient_agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waybill_expenses" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waybill_expenses" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waybill_expenses" ADD FOREIGN KEY ("from_admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waybill_expenses" ADD FOREIGN KEY ("to_admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waybill_expenses" ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "waybill_expenses" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "action_items" ADD FOREIGN KEY ("assigned_to") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "action_items" ADD FOREIGN KEY ("assigned_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "action_items" ADD FOREIGN KEY ("closed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "commission_tiers" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "csr_promotion_thresholds" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "csr_level_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "csr_level_history" ADD FOREIGN KEY ("changed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "csr_performance_monthly" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "csr_performance_monthly" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "csr_performance_monthly" ADD FOREIGN KEY ("commission_tier_id") REFERENCES "commission_tiers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "weekly_bonus_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "weekly_bonus_log" ADD FOREIGN KEY ("paid_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pabbly_reconciliation_log" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_adjustments" ADD FOREIGN KEY ("approved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_ledger" ADD FOREIGN KEY ("agent_id") REFERENCES "agents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_ledger" ADD FOREIGN KEY ("logged_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "department_targets" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "department_targets" ADD FOREIGN KEY ("set_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendors" ADD FOREIGN KEY ("admin_level_1_id") REFERENCES "admin_level_1" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendors" ADD FOREIGN KEY ("admin_level_2_id") REFERENCES "admin_level_2" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vendors" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_categories" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons_learned" ADD FOREIGN KEY ("category_id") REFERENCES "lesson_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons_learned" ADD FOREIGN KEY ("submitted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons_learned" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "escalation_reason_codes" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_escalations" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_escalations" ADD FOREIGN KEY ("reason_code_id") REFERENCES "escalation_reason_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_escalations" ADD FOREIGN KEY ("raised_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_escalations" ADD FOREIGN KEY ("resolved_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "agent_remittance" ADD FOREIGN KEY ("variance_reason_id") REFERENCES "remittance_variance_reason_codes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auditor_spot_checks" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auditor_spot_checks" ADD FOREIGN KEY ("auditor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "auditor_spot_checks" ADD FOREIGN KEY ("check_category_id") REFERENCES "auditor_check_categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "weekly_reports" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "weekly_reports" ADD FOREIGN KEY ("csr_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "weekly_reports" ADD FOREIGN KEY ("generated_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
