SET ROLE jamisan_admin;

BEGIN;

-- =============================================================================
-- Nigeria: 36 States + FCT => admin_level_1
-- =============================================================================
INSERT INTO admin_level_1 (id, country_id, name, code, is_active) VALUES
  ( 1, 1, 'Abia',                  'AB',  true),
  ( 2, 1, 'Adamawa',               'AD',  true),
  ( 3, 1, 'Akwa Ibom',             'AK',  true),
  ( 4, 1, 'Anambra',               'AN',  true),
  ( 5, 1, 'Bauchi',                'BA',  true),
  ( 6, 1, 'Bayelsa',               'BY',  true),
  ( 7, 1, 'Benue',                 'BE',  true),
  ( 8, 1, 'Borno',                 'BO',  true),
  ( 9, 1, 'Cross River',           'CR',  true),
  (10, 1, 'Delta',                 'DE',  true),
  (11, 1, 'Ebonyi',                'EB',  true),
  (12, 1, 'Edo',                   'ED',  true),
  (13, 1, 'Ekiti',                 'EK',  true),
  (14, 1, 'Enugu',                 'EN',  true),
  (15, 1, 'Federal Capital Territory', 'FC', true),
  (16, 1, 'Gombe',                 'GO',  true),
  (17, 1, 'Imo',                   'IM',  true),
  (18, 1, 'Jigawa',                'JI',  true),
  (19, 1, 'Kaduna',                'KD',  true),
  (20, 1, 'Kano',                  'KN',  true),
  (21, 1, 'Katsina',               'KT',  true),
  (22, 1, 'Kebbi',                 'KB',  true),
  (23, 1, 'Kogi',                  'KO',  true),
  (24, 1, 'Kwara',                 'KW',  true),
  (25, 1, 'Lagos',                 'LA',  true),
  (26, 1, 'Nasarawa',              'NA',  true),
  (27, 1, 'Niger',                 'NI',  true),
  (28, 1, 'Ogun',                  'OG',  true),
  (29, 1, 'Ondo',                  'ON',  true),
  (30, 1, 'Osun',                  'OS',  true),
  (31, 1, 'Oyo',                   'OY',  true),
  (32, 1, 'Plateau',               'PL',  true),
  (33, 1, 'Rivers',                'RI',  true),
  (34, 1, 'Sokoto',                'SO',  true),
  (35, 1, 'Taraba',                'TA',  true),
  (36, 1, 'Yobe',                  'YO',  true),
  (37, 1, 'Zamfara',               'ZA',  true);

-- =============================================================================
-- Nigeria: 774 LGAs => admin_level_2
-- =============================================================================

-- Abia (1) - 17 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (1, 'Aba North',         true),
  (1, 'Aba South',         true),
  (1, 'Arochukwu',         true),
  (1, 'Bende',             true),
  (1, 'Ikwuano',           true),
  (1, 'Isiala Ngwa North', true),
  (1, 'Isiala Ngwa South', true),
  (1, 'Isuikwuato',        true),
  (1, 'Obi Ngwa',          true),
  (1, 'Ohafia',            true),
  (1, 'Osisioma',          true),
  (1, 'Ugwunagbo',         true),
  (1, 'Ukwa East',         true),
  (1, 'Ukwa West',         true),
  (1, 'Umuahia North',     true),
  (1, 'Umuahia South',     true),
  (1, 'Umu Nneochi',       true);

-- Adamawa (2) - 21 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (2, 'Demsa',          true),
  (2, 'Fufure',         true),
  (2, 'Ganye',          true),
  (2, 'Gayuk',          true),
  (2, 'Gombi',          true),
  (2, 'Grie',           true),
  (2, 'Hong',           true),
  (2, 'Jada',           true),
  (2, 'Lamurde',        true),
  (2, 'Madagali',       true),
  (2, 'Maiha',          true),
  (2, 'Mayo-Belwa',     true),
  (2, 'Michika',        true),
  (2, 'Mubi North',     true),
  (2, 'Mubi South',     true),
  (2, 'Numan',          true),
  (2, 'Shelleng',       true),
  (2, 'Song',           true),
  (2, 'Toungo',         true),
  (2, 'Yola North',     true),
  (2, 'Yola South',     true);

-- Akwa Ibom (3) - 31 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (3, 'Abak',               true),
  (3, 'Eastern Obolo',      true),
  (3, 'Eket',               true),
  (3, 'Esit Eket',          true),
  (3, 'Essien Udim',        true),
  (3, 'Etim Ekpo',          true),
  (3, 'Etinan',             true),
  (3, 'Ibeno',              true),
  (3, 'Ibesikpo Asutan',    true),
  (3, 'Ibiono-Ibom',        true),
  (3, 'Ika',                true),
  (3, 'Ikono',              true),
  (3, 'Ikot Abasi',         true),
  (3, 'Ikot Ekpene',        true),
  (3, 'Ini',                true),
  (3, 'Itu',                true),
  (3, 'Mbo',                true),
  (3, 'Mkpat-Enin',         true),
  (3, 'Nsit-Atai',          true),
  (3, 'Nsit-Ibom',          true),
  (3, 'Nsit-Ubium',         true),
  (3, 'Obot Akara',         true),
  (3, 'Okobo',              true),
  (3, 'Onna',               true),
  (3, 'Oron',               true),
  (3, 'Oruk Anam',          true),
  (3, 'Udung-Uko',          true),
  (3, 'Ukanafun',           true),
  (3, 'Uruan',              true),
  (3, 'Urue-Offong/Oruko',  true),
  (3, 'Uyo',                true);

-- Anambra (4) - 21 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (4, 'Aguata',           true),
  (4, 'Anambra East',     true),
  (4, 'Anambra West',     true),
  (4, 'Anaocha',          true),
  (4, 'Awka North',       true),
  (4, 'Awka South',       true),
  (4, 'Ayamelum',         true),
  (4, 'Dunukofia',        true),
  (4, 'Ekwusigo',         true),
  (4, 'Idemili North',    true),
  (4, 'Idemili South',    true),
  (4, 'Ihiala',           true),
  (4, 'Njikoka',          true),
  (4, 'Nnewi North',      true),
  (4, 'Nnewi South',      true),
  (4, 'Ogbaru',           true),
  (4, 'Onitsha North',    true),
  (4, 'Onitsha South',    true),
  (4, 'Orumba North',     true),
  (4, 'Orumba South',     true),
  (4, 'Oyi',              true);

-- Bauchi (5) - 20 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (5, 'Alkaleri',      true),
  (5, 'Bauchi',        true),
  (5, 'Bogoro',        true),
  (5, 'Damban',        true),
  (5, 'Darazo',        true),
  (5, 'Dass',          true),
  (5, 'Gamawa',        true),
  (5, 'Ganjuwa',       true),
  (5, 'Giade',         true),
  (5, 'Itas/Gadau',    true),
  (5, 'Jama''are',     true),
  (5, 'Katagum',       true),
  (5, 'Kirfi',         true),
  (5, 'Misau',         true),
  (5, 'Ningi',         true),
  (5, 'Shira',         true),
  (5, 'Tafawa Balewa', true),
  (5, 'Toro',          true),
  (5, 'Warji',         true),
  (5, 'Zaki',          true);

-- Bayelsa (6) - 8 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (6, 'Brass',         true),
  (6, 'Ekeremor',      true),
  (6, 'Kolokuma/Opokuma', true),
  (6, 'Nembe',         true),
  (6, 'Ogbia',         true),
  (6, 'Sagbama',       true),
  (6, 'Southern Ijaw', true),
  (6, 'Yenagoa',       true);

-- Benue (7) - 23 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (7, 'Ado',           true),
  (7, 'Agatu',         true),
  (7, 'Apa',           true),
  (7, 'Buruku',        true),
  (7, 'Gboko',         true),
  (7, 'Guma',          true),
  (7, 'Gwer East',     true),
  (7, 'Gwer West',     true),
  (7, 'Katsina-Ala',   true),
  (7, 'Konshisha',     true),
  (7, 'Kwande',        true),
  (7, 'Logo',          true),
  (7, 'Makurdi',       true),
  (7, 'Obi',           true),
  (7, 'Ogbadibo',      true),
  (7, 'Ohimini',       true),
  (7, 'Oju',           true),
  (7, 'Okpokwu',       true),
  (7, 'Otukpo',        true),
  (7, 'Tarka',         true),
  (7, 'Ukum',          true),
  (7, 'Ushongo',       true),
  (7, 'Vandeikya',     true);

-- Borno (8) - 27 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (8, 'Abadam',        true),
  (8, 'Askira/Uba',    true),
  (8, 'Bama',          true),
  (8, 'Bayo',          true),
  (8, 'Biu',           true),
  (8, 'Chibok',        true),
  (8, 'Damboa',        true),
  (8, 'Dikwa',         true),
  (8, 'Gubio',         true),
  (8, 'Guzamala',      true),
  (8, 'Gwoza',         true),
  (8, 'Hawul',         true),
  (8, 'Jere',          true),
  (8, 'Kaga',          true),
  (8, 'Kala/Balge',    true),
  (8, 'Konduga',       true),
  (8, 'Kukawa',        true),
  (8, 'Kwaya Kusar',   true),
  (8, 'Mafa',          true),
  (8, 'Magumeri',      true),
  (8, 'Maiduguri',     true),
  (8, 'Marte',         true),
  (8, 'Mobbar',        true),
  (8, 'Monguno',       true),
  (8, 'Ngala',         true),
  (8, 'Nganzai',       true),
  (8, 'Shani',         true);

-- Cross River (9) - 18 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (9, 'Abi',           true),
  (9, 'Akamkpa',       true),
  (9, 'Akpabuyo',      true),
  (9, 'Bakassi',       true),
  (9, 'Bekwarra',      true),
  (9, 'Biase',         true),
  (9, 'Boki',          true),
  (9, 'Calabar Municipal', true),
  (9, 'Calabar South', true),
  (9, 'Etung',         true),
  (9, 'Ikom',          true),
  (9, 'Obanliku',      true),
  (9, 'Obubra',        true),
  (9, 'Obudu',         true),
  (9, 'Odukpani',      true),
  (9, 'Ogoja',         true),
  (9, 'Yakuur',        true),
  (9, 'Yala',          true);

-- Delta (10) - 25 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (10, 'Aniocha North',   true),
  (10, 'Aniocha South',   true),
  (10, 'Bomadi',          true),
  (10, 'Burutu',          true),
  (10, 'Ethiope East',    true),
  (10, 'Ethiope West',    true),
  (10, 'Ika North East',  true),
  (10, 'Ika South',       true),
  (10, 'Isoko North',     true),
  (10, 'Isoko South',     true),
  (10, 'Ndokwa East',     true),
  (10, 'Ndokwa West',     true),
  (10, 'Okpe',            true),
  (10, 'Oshimili North',  true),
  (10, 'Oshimili South',  true),
  (10, 'Patani',          true),
  (10, 'Sapele',          true),
  (10, 'Udu',             true),
  (10, 'Ughelli North',   true),
  (10, 'Ughelli South',   true),
  (10, 'Ukwuani',         true),
  (10, 'Uvwie',           true),
  (10, 'Warri North',     true),
  (10, 'Warri South',     true),
  (10, 'Warri South West',true);

-- Ebonyi (11) - 13 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (11, 'Abakaliki',        true),
  (11, 'Afikpo North',     true),
  (11, 'Afikpo South',     true),
  (11, 'Ebonyi',           true),
  (11, 'Ezza North',       true),
  (11, 'Ezza South',       true),
  (11, 'Ikwo',             true),
  (11, 'Ishielu',          true),
  (11, 'Ivo',              true),
  (11, 'Izzi',             true),
  (11, 'Ohaozara',         true),
  (11, 'Ohaukwu',          true),
  (11, 'Onicha',           true);

-- Edo (12) - 18 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (12, 'Akoko-Edo',        true),
  (12, 'Egor',             true),
  (12, 'Esan Central',     true),
  (12, 'Esan North-East',  true),
  (12, 'Esan South-East',  true),
  (12, 'Esan West',        true),
  (12, 'Etsako Central',   true),
  (12, 'Etsako East',      true),
  (12, 'Etsako West',      true),
  (12, 'Igueben',          true),
  (12, 'Ikpoba-Okha',      true),
  (12, 'Orhionmwon',       true),
  (12, 'Oredo',            true),
  (12, 'Ovia North-East',  true),
  (12, 'Ovia South-West',  true),
  (12, 'Owan East',        true),
  (12, 'Owan West',        true),
  (12, 'Uhunmwonde',       true);

-- Ekiti (13) - 16 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (13, 'Ado Ekiti',        true),
  (13, 'Efon',             true),
  (13, 'Ekiti East',       true),
  (13, 'Ekiti South-West', true),
  (13, 'Ekiti West',       true),
  (13, 'Emure',            true),
  (13, 'Gbonyin',          true),
  (13, 'Ido/Osi',          true),
  (13, 'Ijero',            true),
  (13, 'Ikere',            true),
  (13, 'Ikole',            true),
  (13, 'Ilejemeje',        true),
  (13, 'Irepodun/Ifelodun',true),
  (13, 'Ise/Orun',         true),
  (13, 'Moba',             true),
  (13, 'Oye',              true);

-- Enugu (14) - 17 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (14, 'Aninri',           true),
  (14, 'Awgu',             true),
  (14, 'Enugu East',       true),
  (14, 'Enugu North',      true),
  (14, 'Enugu South',      true),
  (14, 'Ezeagu',           true),
  (14, 'Igbo Etiti',       true),
  (14, 'Igbo Eze North',   true),
  (14, 'Igbo Eze South',   true),
  (14, 'Isi Uzo',          true),
  (14, 'Nkanu East',       true),
  (14, 'Nkanu West',       true),
  (14, 'Nsukka',           true),
  (14, 'Oji River',        true),
  (14, 'Udenu',            true),
  (14, 'Udi',              true),
  (14, 'Uzo Uwani',        true);

-- Federal Capital Territory (15) - 6 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (15, 'Abaji',            true),
  (15, 'Bwari',            true),
  (15, 'Gwagwalada',       true),
  (15, 'Kuje',             true),
  (15, 'Kwali',            true),
  (15, 'Municipal Area Council', true);

-- Gombe (16) - 11 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (16, 'Akko',             true),
  (16, 'Balanga',          true),
  (16, 'Billiri',          true),
  (16, 'Dukku',            true),
  (16, 'Funakaye',         true),
  (16, 'Gombe',            true),
  (16, 'Kaltungo',         true),
  (16, 'Kwami',            true),
  (16, 'Nafada',           true),
  (16, 'Shongom',          true),
  (16, 'Yamaltu/Deba',     true);

-- Imo (17) - 27 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (17, 'Aboh Mbaise',      true),
  (17, 'Ahiazu Mbaise',    true),
  (17, 'Ehime Mbano',      true),
  (17, 'Ezinihitte',       true),
  (17, 'Ideato North',     true),
  (17, 'Ideato South',     true),
  (17, 'Ihitte/Uboma',     true),
  (17, 'Ikeduru',          true),
  (17, 'Isiala Mbano',     true),
  (17, 'Isu',              true),
  (17, 'Mbaitoli',         true),
  (17, 'Ngor Okpala',      true),
  (17, 'Njaba',            true),
  (17, 'Nkwerre',          true),
  (17, 'Nwangele',         true),
  (17, 'Obowo',            true),
  (17, 'Oguta',            true),
  (17, 'Ohaji/Egbema',     true),
  (17, 'Okigwe',           true),
  (17, 'Onuimo',           true),
  (17, 'Orlu',             true),
  (17, 'Orsu',             true),
  (17, 'Oru East',         true),
  (17, 'Oru West',         true),
  (17, 'Owerri Municipal', true),
  (17, 'Owerri North',     true),
  (17, 'Owerri West',      true);

-- Jigawa (18) - 27 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (18, 'Auyo',             true),
  (18, 'Babura',           true),
  (18, 'Biriniwa',         true),
  (18, 'Birnin Kudu',      true),
  (18, 'Buji',             true),
  (18, 'Dutse',            true),
  (18, 'Gagarawa',         true),
  (18, 'Garki',            true),
  (18, 'Gumel',            true),
  (18, 'Guri',             true),
  (18, 'Gwaram',           true),
  (18, 'Gwiwa',            true),
  (18, 'Hadejia',          true),
  (18, 'Jahun',            true),
  (18, 'Kafin Hausa',      true),
  (18, 'Kaugama',          true),
  (18, 'Kazaure',          true),
  (18, 'Kiri Kasama',      true),
  (18, 'Kiyawa',           true),
  (18, 'Maigatari',        true),
  (18, 'Malam Madori',     true),
  (18, 'Miga',             true),
  (18, 'Ringim',           true),
  (18, 'Roni',             true),
  (18, 'Sule Tankarkar',   true),
  (18, 'Taura',            true),
  (18, 'Yankwashi',        true);

-- Kaduna (19) - 23 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (19, 'Birnin Gwari',     true),
  (19, 'Chikun',           true),
  (19, 'Giwa',             true),
  (19, 'Igabi',            true),
  (19, 'Ikara',            true),
  (19, 'Jaba',             true),
  (19, 'Jema''a',          true),
  (19, 'Kachia',           true),
  (19, 'Kaduna North',     true),
  (19, 'Kaduna South',     true),
  (19, 'Kagarko',          true),
  (19, 'Kajuru',           true),
  (19, 'Kaura',            true),
  (19, 'Kauru',            true),
  (19, 'Kubau',            true),
  (19, 'Kudan',            true),
  (19, 'Lere',             true),
  (19, 'Makarfi',          true),
  (19, 'Sabon Gari',       true),
  (19, 'Sanga',            true),
  (19, 'Soba',             true),
  (19, 'Zangon Kataf',     true),
  (19, 'Zaria',            true);

-- Kano (20) - 44 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (20, 'Ajingi',           true),
  (20, 'Albasu',           true),
  (20, 'Bagwai',           true),
  (20, 'Bebeji',           true),
  (20, 'Bichi',            true),
  (20, 'Bunkure',          true),
  (20, 'Dala',             true),
  (20, 'Dambatta',         true),
  (20, 'Dawakin Kudu',     true),
  (20, 'Dawakin Tofa',     true),
  (20, 'Doguwa',           true),
  (20, 'Fagge',            true),
  (20, 'Gabasawa',         true),
  (20, 'Garko',            true),
  (20, 'Garun Mallam',     true),
  (20, 'Gaya',             true),
  (20, 'Gezawa',           true),
  (20, 'Gwale',            true),
  (20, 'Gwarzo',           true),
  (20, 'Kabo',             true),
  (20, 'Kano Municipal',   true),
  (20, 'Karaye',           true),
  (20, 'Kibiya',           true),
  (20, 'Kiru',             true),
  (20, 'Kumbotso',         true),
  (20, 'Kunchi',           true),
  (20, 'Kura',             true),
  (20, 'Madobi',           true),
  (20, 'Makoda',           true),
  (20, 'Minjibir',         true),
  (20, 'Nasarawa',         true),
  (20, 'Rano',             true),
  (20, 'Rimin Gado',       true),
  (20, 'Rogo',             true),
  (20, 'Shanono',          true),
  (20, 'Sumaila',          true),
  (20, 'Takai',            true),
  (20, 'Tarauni',          true),
  (20, 'Tofa',             true),
  (20, 'Tsanyawa',         true),
  (20, 'Tudun Wada',       true),
  (20, 'Ungogo',           true),
  (20, 'Warawa',           true),
  (20, 'Wudil',            true);

-- Katsina (21) - 34 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (21, 'Bakori',           true),
  (21, 'Batagarawa',       true),
  (21, 'Batsari',          true),
  (21, 'Baure',            true),
  (21, 'Bindawa',          true),
  (21, 'Charanchi',        true),
  (21, 'Dan Musa',         true),
  (21, 'Dandume',          true),
  (21, 'Danja',            true),
  (21, 'Daura',            true),
  (21, 'Dutsi',            true),
  (21, 'Dutsin-Ma',        true),
  (21, 'Faskari',          true),
  (21, 'Funtua',           true),
  (21, 'Ingawa',           true),
  (21, 'Jibia',            true),
  (21, 'Kafur',            true),
  (21, 'Kaita',            true),
  (21, 'Kankara',          true),
  (21, 'Kankia',           true),
  (21, 'Katsina',          true),
  (21, 'Kurfi',            true),
  (21, 'Kusada',           true),
  (21, 'Mai''Adua',        true),
  (21, 'Malumfashi',       true),
  (21, 'Mani',             true),
  (21, 'Mashi',            true),
  (21, 'Matazu',           true),
  (21, 'Musawa',           true),
  (21, 'Rimi',             true),
  (21, 'Sabuwa',           true),
  (21, 'Safana',           true),
  (21, 'Sandamu',          true),
  (21, 'Zango',            true);

-- Kebbi (22) - 21 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (22, 'Aleiro',           true),
  (22, 'Arewa Dandi',      true),
  (22, 'Argungu',          true),
  (22, 'Augie',            true),
  (22, 'Bagudo',           true),
  (22, 'Birnin Kebbi',     true),
  (22, 'Bunza',            true),
  (22, 'Dandi',            true),
  (22, 'Fakai',            true),
  (22, 'Gwandu',           true),
  (22, 'Jega',             true),
  (22, 'Kalgo',            true),
  (22, 'Koko/Besse',       true),
  (22, 'Maiyama',          true),
  (22, 'Ngaski',           true),
  (22, 'Sakaba',           true),
  (22, 'Shanga',           true),
  (22, 'Suru',             true),
  (22, 'Wasagu/Danko',     true),
  (22, 'Yauri',            true),
  (22, 'Zuru',             true);

-- Kogi (23) - 21 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (23, 'Adavi',            true),
  (23, 'Ajaokuta',         true),
  (23, 'Ankpa',            true),
  (23, 'Bassa',            true),
  (23, 'Dekina',           true),
  (23, 'Ibaji',            true),
  (23, 'Idah',             true),
  (23, 'Igalamela-Odolu',  true),
  (23, 'Ijumu',            true),
  (23, 'Kabba/Bunu',       true),
  (23, 'Kogi',             true),
  (23, 'Lokoja',           true),
  (23, 'Mopa-Muro',        true),
  (23, 'Ofu',              true),
  (23, 'Ogori/Magongo',    true),
  (23, 'Okehi',            true),
  (23, 'Okene',            true),
  (23, 'Olamaboro',        true),
  (23, 'Omala',            true),
  (23, 'Yagba East',       true),
  (23, 'Yagba West',       true);

-- Kwara (24) - 16 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (24, 'Asa',              true),
  (24, 'Baruten',          true),
  (24, 'Edu',              true),
  (24, 'Ekiti',            true),
  (24, 'Ifelodun',         true),
  (24, 'Ilorin East',      true),
  (24, 'Ilorin South',     true),
  (24, 'Ilorin West',      true),
  (24, 'Irepodun',         true),
  (24, 'Isin',             true),
  (24, 'Kaiama',           true),
  (24, 'Moro',             true),
  (24, 'Offa',             true),
  (24, 'Oke Ero',          true),
  (24, 'Oyun',             true),
  (24, 'Pategi',           true);

-- Lagos (25) - 20 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (25, 'Agege',            true),
  (25, 'Ajeromi-Ifelodun', true),
  (25, 'Alimosho',         true),
  (25, 'Amuwo-Odofin',     true),
  (25, 'Apapa',            true),
  (25, 'Badagry',          true),
  (25, 'Epe',              true),
  (25, 'Eti-Osa',          true),
  (25, 'Ibeju-Lekki',      true),
  (25, 'Ifako-Ijaiye',     true),
  (25, 'Ikeja',            true),
  (25, 'Ikorodu',          true),
  (25, 'Kosofe',           true),
  (25, 'Lagos Island',     true),
  (25, 'Lagos Mainland',   true),
  (25, 'Mushin',           true),
  (25, 'Ojo',              true),
  (25, 'Oshodi-Isolo',     true),
  (25, 'Shomolu',          true),
  (25, 'Surulere',         true);

-- Nasarawa (26) - 13 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (26, 'Akwanga',          true),
  (26, 'Awe',              true),
  (26, 'Doma',             true),
  (26, 'Karu',             true),
  (26, 'Keana',            true),
  (26, 'Keffi',            true),
  (26, 'Kokona',           true),
  (26, 'Lafia',            true),
  (26, 'Nasarawa',         true),
  (26, 'Nasarawa Egon',    true),
  (26, 'Obi',              true),
  (26, 'Toto',             true),
  (26, 'Wamba',            true);

-- Niger (27) - 25 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (27, 'Agaie',            true),
  (27, 'Agwara',           true),
  (27, 'Bida',             true),
  (27, 'Borgu',            true),
  (27, 'Bosso',            true),
  (27, 'Chanchaga',        true),
  (27, 'Edati',            true),
  (27, 'Gbako',            true),
  (27, 'Gurara',           true),
  (27, 'Katcha',           true),
  (27, 'Kontagora',        true),
  (27, 'Lapai',            true),
  (27, 'Lavun',            true),
  (27, 'Magama',           true),
  (27, 'Mariga',           true),
  (27, 'Mashegu',          true),
  (27, 'Mokwa',            true),
  (27, 'Moya',             true),
  (27, 'Paikoro',          true),
  (27, 'Rafi',             true),
  (27, 'Rijau',            true),
  (27, 'Shiroro',          true),
  (27, 'Suleja',           true),
  (27, 'Tafa',             true),
  (27, 'Wushishi',         true);

-- Ogun (28) - 20 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (28, 'Abeokuta North',   true),
  (28, 'Abeokuta South',   true),
  (28, 'Ado-Odo/Ota',      true),
  (28, 'Egbado North',     true),
  (28, 'Egbado South',     true),
  (28, 'Ewekoro',          true),
  (28, 'Ifo',              true),
  (28, 'Ijebu East',       true),
  (28, 'Ijebu North',      true),
  (28, 'Ijebu North East', true),
  (28, 'Ijebu Ode',        true),
  (28, 'Ikenne',           true),
  (28, 'Imeko Afon',       true),
  (28, 'Ipokia',           true),
  (28, 'Obafemi Owode',    true),
  (28, 'Odeda',            true),
  (28, 'Odogbolu',         true),
  (28, 'Ogun Waterside',   true),
  (28, 'Remo North',       true),
  (28, 'Shagamu',          true);

-- Ondo (29) - 18 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (29, 'Akoko North-East', true),
  (29, 'Akoko North-West', true),
  (29, 'Akoko South-East', true),
  (29, 'Akoko South-West', true),
  (29, 'Akure North',      true),
  (29, 'Akure South',      true),
  (29, 'Ese-Odo',          true),
  (29, 'Idanre',           true),
  (29, 'Ifedore',          true),
  (29, 'Ilaje',            true),
  (29, 'Ile Oluji/Okeigbo',true),
  (29, 'Irele',            true),
  (29, 'Odigbo',           true),
  (29, 'Okitipupa',        true),
  (29, 'Ondo East',        true),
  (29, 'Ondo West',        true),
  (29, 'Ose',              true),
  (29, 'Owo',              true);

-- Osun (30) - 30 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (30, 'Aiyedaade',        true),
  (30, 'Aiyedire',         true),
  (30, 'Atakumosa East',   true),
  (30, 'Atakumosa West',   true),
  (30, 'Boluwaduro',       true),
  (30, 'Boripe',           true),
  (30, 'Ede North',        true),
  (30, 'Ede South',        true),
  (30, 'Egbedore',         true),
  (30, 'Ejigbo',           true),
  (30, 'Ife Central',      true),
  (30, 'Ife East',         true),
  (30, 'Ife North',        true),
  (30, 'Ife South',        true),
  (30, 'Ifedayo',          true),
  (30, 'Ifelodun',         true),
  (30, 'Ila',              true),
  (30, 'Ilesa East',       true),
  (30, 'Ilesa West',       true),
  (30, 'Irepodun',         true),
  (30, 'Irewole',          true),
  (30, 'Isokan',           true),
  (30, 'Iwo',              true),
  (30, 'Obokun',           true),
  (30, 'Odo Otin',         true),
  (30, 'Ola Oluwa',        true),
  (30, 'Olorunda',         true),
  (30, 'Oriade',           true),
  (30, 'Orolu',            true),
  (30, 'Osogbo',           true);

-- Oyo (31) - 33 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (31, 'Afijio',           true),
  (31, 'Akinyele',         true),
  (31, 'Atiba',            true),
  (31, 'Atisbo',           true),
  (31, 'Egbeda',           true),
  (31, 'Ibadan North',     true),
  (31, 'Ibadan North-East',true),
  (31, 'Ibadan North-West',true),
  (31, 'Ibadan South-East',true),
  (31, 'Ibadan South-West',true),
  (31, 'Ibarapa Central',  true),
  (31, 'Ibarapa East',     true),
  (31, 'Ibarapa North',    true),
  (31, 'Ido',              true),
  (31, 'Irepo',            true),
  (31, 'Iseyin',           true),
  (31, 'Itesiwaju',        true),
  (31, 'Iwajowa',          true),
  (31, 'Kajola',           true),
  (31, 'Lagelu',           true),
  (31, 'Ogbomosho North',  true),
  (31, 'Ogbomosho South',  true),
  (31, 'Ogo Oluwa',        true),
  (31, 'Olorunsogo',       true),
  (31, 'Oluyole',          true),
  (31, 'Ona Ara',          true),
  (31, 'Orelope',          true),
  (31, 'Ori Ire',          true),
  (31, 'Oyo East',         true),
  (31, 'Oyo West',         true),
  (31, 'Saki East',        true),
  (31, 'Saki West',        true),
  (31, 'Surulere',         true);

-- Plateau (32) - 17 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (32, 'Barkin Ladi',      true),
  (32, 'Bassa',            true),
  (32, 'Bokkos',           true),
  (32, 'Jos East',         true),
  (32, 'Jos North',        true),
  (32, 'Jos South',        true),
  (32, 'Kanam',            true),
  (32, 'Kanke',            true),
  (32, 'Langtang North',   true),
  (32, 'Langtang South',   true),
  (32, 'Mangu',            true),
  (32, 'Mikang',           true),
  (32, 'Pankshin',         true),
  (32, 'Qua''an Pan',      true),
  (32, 'Riyom',            true),
  (32, 'Shendam',          true),
  (32, 'Wase',             true);

-- Rivers (33) - 23 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (33, 'Abua/Odual',       true),
  (33, 'Ahoada East',      true),
  (33, 'Ahoada West',      true),
  (33, 'Akuku-Toru',       true),
  (33, 'Andoni',           true),
  (33, 'Asari-Toru',       true),
  (33, 'Bonny',            true),
  (33, 'Degema',           true),
  (33, 'Eleme',            true),
  (33, 'Emohua',           true),
  (33, 'Etche',            true),
  (33, 'Gokana',           true),
  (33, 'Ikwerre',          true),
  (33, 'Khana',            true),
  (33, 'Obio/Akpor',       true),
  (33, 'Ogba/Egbema/Ndoni',true),
  (33, 'Ogu/Bolo',         true),
  (33, 'Okrika',           true),
  (33, 'Omuma',            true),
  (33, 'Opobo/Nkoro',      true),
  (33, 'Oyigbo',           true),
  (33, 'Port Harcourt',    true),
  (33, 'Tai',              true);

-- Sokoto (34) - 23 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (34, 'Binji',            true),
  (34, 'Bodinga',          true),
  (34, 'Dange Shuni',      true),
  (34, 'Gada',             true),
  (34, 'Goronyo',          true),
  (34, 'Gudu',             true),
  (34, 'Gwadabawa',        true),
  (34, 'Illela',           true),
  (34, 'Isa',              true),
  (34, 'Kebbe',            true),
  (34, 'Kware',            true),
  (34, 'Rabah',            true),
  (34, 'Sabon Birni',      true),
  (34, 'Shagari',          true),
  (34, 'Silame',           true),
  (34, 'Sokoto North',     true),
  (34, 'Sokoto South',     true),
  (34, 'Tambuwal',         true),
  (34, 'Tangaza',          true),
  (34, 'Tureta',           true),
  (34, 'Wamako',           true),
  (34, 'Wurno',            true),
  (34, 'Yabo',             true);

-- Taraba (35) - 16 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (35, 'Ardo Kola',        true),
  (35, 'Bali',             true),
  (35, 'Donga',            true),
  (35, 'Gashaka',          true),
  (35, 'Gassol',           true),
  (35, 'Ibi',              true),
  (35, 'Jalingo',          true),
  (35, 'Karim Lamido',     true),
  (35, 'Kumi',             true),
  (35, 'Lau',              true),
  (35, 'Sardauna',         true),
  (35, 'Takum',            true),
  (35, 'Ussa',             true),
  (35, 'Wukari',           true),
  (35, 'Yorro',            true),
  (35, 'Zing',             true);

-- Yobe (36) - 17 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (36, 'Bade',             true),
  (36, 'Bursari',          true),
  (36, 'Damaturu',         true),
  (36, 'Fika',             true),
  (36, 'Fune',             true),
  (36, 'Geidam',           true),
  (36, 'Gujba',            true),
  (36, 'Gulani',           true),
  (36, 'Jakusko',          true),
  (36, 'Karasuwa',         true),
  (36, 'Machina',          true),
  (36, 'Nangere',          true),
  (36, 'Nguru',            true),
  (36, 'Potiskum',         true),
  (36, 'Tarmua',           true),
  (36, 'Yunusari',         true),
  (36, 'Yusufari',         true);

-- Zamfara (37) - 14 LGAs
INSERT INTO admin_level_2 (admin_level_1_id, name, is_active) VALUES
  (37, 'Anka',                    true),
  (37, 'Bakura',                  true),
  (37, 'Birnin Magaji/Kiyawa',    true),
  (37, 'Bukkuyum',                true),
  (37, 'Bungudu',                 true),
  (37, 'Gummi',                   true),
  (37, 'Gusau',                   true),
  (37, 'Kaura Namoda',            true),
  (37, 'Maradun',                 true),
  (37, 'Maru',                    true),
  (37, 'Shinkafi',                true),
  (37, 'Talata Mafara',           true),
  (37, 'Tsafe',                   true),
  (37, 'Zurmi',                   true);

COMMIT;

SELECT 'admin_level_1' AS tbl, COUNT(*) AS cnt FROM admin_level_1
UNION ALL
SELECT 'admin_level_2', COUNT(*) FROM admin_level_2;
